=== uo289769/sew/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified" targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="largura" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="puntos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="largura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="hora" type="xs:time" />
	<xs:element name="vueltas" type="xs:integer" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:float" />
	<xs:element name="latitud" type="xs:float" />
	<xs:element name="altitud" type="xs:float" />
	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
				<xs:element ref="distancia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="sectorTipo" />
	<xs:simpleType name="sectorTipo">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="3" />
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== uo289769/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd">

    <circuito>
        <nombre>Marina Bay</nombre>
        <largura unidades="km">5065</largura>
        <anchura unidades="m">10</anchura>
        <fecha>2024-09-22</fecha>
        <hora>14:00:00</hora>
        <vueltas>62</vueltas>
        <localidad>Singapur</localidad>
        <pais>Singapur</pais>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Circuito_callejero_de_Marina_Bay</referencia>
            <referencia>https://lebalap.academy/f1/circuito-de-singapur/</referencia>
            <referencia>http://www.ligafantasticaf1.es/circuitos-f1/singapur.php</referencia>
        </referencias>
        <fotos>
            <foto>marina-bay-circuit.jpeg</foto>
        </fotos>
        <videos></videos>
        <coordenadas>
            <longitud>103.86416549383493</longitud>
            <latitud>1.2916970048725602</latitud>
            <altitud>4.15</altitud>
        </coordenadas>
        <puntos>
            <punto>
                <coordenadas>
                    <longitud>103.86416424200401</longitud>
                    <latitud>1.291696711158246</latitud>
                    <altitud>3.7</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">0</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86378440164624</longitud>
                    <latitud>1.2942826091513782</latitud>
                    <altitud>4.07</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">288.35</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86365301161858</longitud>
                    <latitud>1.2943429340658352</latitud>
                    <altitud>4.05</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">17.23</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86323683819732</longitud>
                    <latitud>1.294347498631495</latitud>
                    <altitud>4</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">48.06</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86278785162442</longitud>
                    <latitud>1.2948141385645269</latitud>
                    <altitud>3.65</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">71.08</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86248409145357</longitud>
                    <latitud>1.2947249778864582</latitud>
                    <altitud>3.57</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">35.09</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.8624283623637</longitud>
                    <latitud>1.2937388445015845</latitud>
                    <altitud>2.92</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">111.23</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86288055289671</longitud>
                    <latitud>1.2924133280024066</latitud>
                    <altitud>4.29</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">156.29</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86293209141103</longitud>
                    <latitud>1.2916728604730565</latitud>
                    <altitud>4.01</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">79.32</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86279357436746</longitud>
                    <latitud>1.2914030570158412</latitud>
                    <altitud>3.96</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">34.65</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86241089215544</longitud>
                    <latitud>1.2912397504703086</latitud>
                    <altitud>4.04</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">45.27</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85885156909383</longitud>
                    <latitud>1.2914611700161405</latitud>
                    <altitud>4.43</altitud>
                </coordenadas>
                <sector>1</sector>
                <distancia unidades="m">396.13</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85588048148544</longitud>
                    <latitud>1.293113149043403</latitud>
                    <altitud>4.70</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">378.14</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85490137006008</longitud>
                    <latitud>1.2913796113336937</latitud>
                    <altitud>4.97</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">220.8</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85362292207954</longitud>
                    <latitud>1.29260834687005</latitud>
                    <altitud>5.78</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">195.77</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85317997442313</longitud>
                    <latitud>1.2923948365245408</latitud>
                    <altitud>5.59</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">54.5</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85143874244406</longitud>
                    <latitud>1.2890852161443935</latitud>
                    <altitud>5.31</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">414.48</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85238153601746</longitud>
                    <latitud>1.288305235855774</latitud>
                    <altitud>5.05</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">51.84</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.852478328111</longitud>
                    <latitud>1.287728094564119</latitud>
                    <altitud>5.67</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">64.55</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85332424664797</longitud>
                    <latitud>1.287024496994362</latitud>
                    <altitud>6.21</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">124.02</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85384347663643</longitud>
                    <latitud>1.2863769851698583</latitud>
                    <altitud>7.94</altitud>
                </coordenadas>
                <sector>2</sector>
                <distancia unidades="m">90.4</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.8549495396649</longitud>
                    <latitud>1.2913415437369349</latitud>
                    <altitud>4.97</altitud>
                </coordenadas>
                <sector>3</sector>
                <distancia unidades="m">562.33</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.85683484318153</longitud>
                    <latitud>1.289789019680129</latitud>
                    <altitud>4.93</altitud>
                </coordenadas>
                <sector>3</sector>
                <distancia unidades="m">270.94</distancia>
            </punto>
            <punto>
                <coordenadas>
                    <longitud>103.86118142043998</longitud>
                    <latitud>1.289507169483381</latitud>
                    <altitud>4.66</altitud>
                </coordenadas>
                <sector>3</sector>
                <distancia unidades="m">484.58</distancia>
            </punto>
            <punto>
                <coordenadas>
